# Generated by Django 2.2.19 on 2022-08-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220804_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='slag',
            new_name='slug',
        ),
    ]
